/**
 * Copyright 2022
 * Andrés Segura-Tinoco
 * Information Retrieval Group at Universidad Autonoma de Madrid
 *
 * This is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This software is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * the current software. If not, see <http://www.gnu.org/licenses/>.
 */
package es.uam.irg.ir.gui;

import es.uam.irg.decidemadrid.entities.DMComment;
import es.uam.irg.decidemadrid.entities.DMProposal;
import es.uam.irg.nlp.am.arguments.Argument;
import es.uam.irg.nlp.am.arguments.ArgumentLinker;
import es.uam.irg.nlp.am.arguments.ArgumentPattern;
import es.uam.irg.nlp.am.arguments.Sentence;
import es.uam.irg.utils.StringUtils;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 */
public class AnnotationForm extends javax.swing.JDialog {

    private final DataModel model;
    private String sentText;
    private String sentClaim;
    private String sentPremise;
    private final Map<String, List<String>> taxonomy;
    private String argumentId;
    private int commentId;
    private int parentId;
    private int userId;
    private boolean result;

    /**
     * Creates new form ArgumentForm
     *
     * @param model
     */
    public AnnotationForm(DataModel model) {
        initComponents();
        this.model = model;
        this.taxonomy = model.getArgumentTaxonomy();
        this.commentId = 0;
        this.userId = 0;
        this.parentId = 0;
        this.argumentId = "";
        this.sentText = "";
        this.sentClaim = "";
        this.sentPremise = "";
        this.result = false;
    }

    public boolean getStatus() {
        return this.result;
    }

    /**
     *
     * @param id
     */
    public void showProposal(int id) {
        DMProposal proposal = model.getProposal(id);

        if (proposal != null) {
            // Save global ids
            int proposalId = proposal.getId();
            this.commentId = -1;
            this.userId = proposal.getUserId();
            this.parentId = -1;
            this.argumentId = proposalId + "-0-1-1";

            this.sentText = proposal.getSummary();
            this.cmbType.setSelectedItem("Proposal");
            this.txtDate.setText(proposal.getDate());
            this.txtMessage.setText(sentText);
            this.setVisible(true);
        }
    }

    /**
     *
     * @param id
     */
    public void showComment(int id) {
        DMComment comment = model.getComment(id);

        if (comment != null) {
            // Save global ids
            int proposalId = comment.getProposalId();
            this.commentId = comment.getId();
            this.userId = comment.getUserId();
            this.parentId = comment.getParentId();
            this.argumentId = proposalId + "-" + commentId + "-1-1";

            this.sentText = comment.getText();
            this.cmbType.setSelectedItem("Comment");
            this.txtDate.setText(comment.getDate());
            this.txtMessage.setText(sentText);
            this.setVisible(true);
        }
    }

    /**
     *
     */
    private void highlightArgument() {
        String sentence = this.sentText;

        if (!this.sentClaim.isEmpty()) {
            String hlClaim = model.getFormatter().highlightClaim(this.sentClaim);
            sentence = sentence.replace(this.sentClaim, hlClaim);
        }

        if (!this.sentPremise.isEmpty()) {
            String hlPremise = model.getFormatter().highlightPremise(this.sentPremise);
            sentence = sentence.replace(this.sentPremise, hlPremise);
        }

        this.txtMessage.setText(sentence);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblType = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        cmbType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextPane();
        btnClear = new javax.swing.JButton();
        btnClaim = new javax.swing.JButton();
        lblRelation = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbSubCategory = new javax.swing.JComboBox<>();
        btnPremise = new javax.swing.JButton();
        lblLabel = new javax.swing.JLabel();
        cmbLabel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Arguments Configuration Form");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblType.setText("Type:");

        lblDate.setText("Date:");

        txtDate.setEditable(false);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Proposal", "Comment" }));
        cmbType.setEnabled(false);

        txtMessage.setEditable(false);
        txtMessage.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(txtMessage);

        btnClear.setText("Clear");
        btnClear.setToolTipText("Clear the configured declarations.");
        btnClear.setMaximumSize(new java.awt.Dimension(60, 23));
        btnClear.setMinimumSize(new java.awt.Dimension(60, 23));
        btnClear.setPreferredSize(new java.awt.Dimension(60, 23));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClaim.setText("Claim");
        btnClaim.setToolTipText("Mark the selected text as a claim.");
        btnClaim.setMaximumSize(new java.awt.Dimension(70, 23));
        btnClaim.setMinimumSize(new java.awt.Dimension(70, 23));
        btnClaim.setPreferredSize(new java.awt.Dimension(70, 23));
        btnClaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimActionPerformed(evt);
            }
        });

        lblRelation.setText("Relation:");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(None)", "Cause", "Clarification", "Consequence", "Contrast", "Elaboration" }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        cmbSubCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(None)" }));

        btnPremise.setText("Premise");
        btnPremise.setMaximumSize(new java.awt.Dimension(72, 23));
        btnPremise.setMinimumSize(new java.awt.Dimension(70, 23));
        btnPremise.setPreferredSize(new java.awt.Dimension(72, 23));
        btnPremise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremiseActionPerformed(evt);
            }
        });

        lblLabel.setText("Label:");

        cmbLabel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relevant", "Valid", "Not valid" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblType)
                        .addGap(18, 18, 18)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblDate)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPremise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblRelation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbSubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClaim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRelation)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPremise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.sentClaim = "";
        this.sentPremise = "";
        this.txtMessage.setText(sentText);
        this.cmbCategory.setSelectedIndex(0);
        this.cmbLabel.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     *
     * @param evt
     */
    private void btnClaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimActionPerformed
        // TODO add your handling code here:
        this.sentClaim = this.txtMessage.getSelectedText();
        highlightArgument();
    }//GEN-LAST:event_btnClaimActionPerformed

    /**
     *
     * @param evt
     */
    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
        this.cmbSubCategory.removeAllItems();
        String currCategory = this.cmbCategory.getSelectedItem().toString();

        if (taxonomy.containsKey(currCategory)) {
            List<String> items = taxonomy.get(currCategory);
            items.forEach(item -> {
                this.cmbSubCategory.addItem(item);
            });
        }
    }//GEN-LAST:event_cmbCategoryActionPerformed

    /**
     *
     * @param evt
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (validation()) {
            String category = this.cmbCategory.getSelectedItem().toString();
            String subCategory = this.cmbSubCategory.getSelectedItem().toString();
            String label = this.cmbLabel.getSelectedItem().toString();
            saveArgument(argumentId, userId, commentId, parentId, this.sentText, this.sentClaim, this.sentPremise, category, subCategory, label);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Error! You must enter all the elements of the argument.", "Error dialog", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPremiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremiseActionPerformed
        // TODO add your handling code here:
        this.sentPremise = this.txtMessage.getSelectedText();
        highlightArgument();
    }//GEN-LAST:event_btnPremiseActionPerformed

    /**
     *
     * @param argumentId
     * @param userId
     * @param commentId
     * @param parentId
     * @param text
     * @param claim
     * @param premise
     * @param category
     * @param subCategory
     * @param label
     * @return
     */
    private void saveArgument(String argumentId, int userId, int commentId, int parentId, String text, String claim, String premise, String category, String subCategory, String label) {
        Sentence majorClaim = new Sentence();
        Sentence sClaim = new Sentence(claim);
        Sentence sPremise = new Sentence(premise);
        ArgumentLinker linker = new ArgumentLinker(category, subCategory, "", "");
        ArgumentPattern sentPattern = new ArgumentPattern("[manual]", 1);
        Argument arg = new Argument(argumentId, userId, commentId, parentId, text, false, sClaim, sPremise, "", linker, sentPattern, "");
        arg.setMajorClaim(majorClaim);

        System.out.println(">> Save/update argument");
        this.result = model.saveArgument(arg, label.toUpperCase());
    }

    /**
     * Form validation method.
     *
     * @return
     */
    private boolean validation() {
        if (StringUtils.isEmpty(this.sentClaim) || StringUtils.isEmpty(this.sentPremise) || this.cmbCategory.getSelectedIndex() == 0) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaim;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnPremise;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbLabel;
    private javax.swing.JComboBox<String> cmbSubCategory;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JLabel lblRelation;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextPane txtMessage;
    // End of variables declaration//GEN-END:variables

}
